import { type RouteConfig, index, route, layout } from "@react-router/dev/routes";

export default [
  // Public routes
  route("login", "routes/login.tsx"),
  route("ui-concept-a", "routes/ui-concept-a.tsx"),
  route("ui-concept-b", "routes/ui-concept-b.tsx"),
  route("ui-concept-c", "routes/ui-concept-c.tsx"),

  // Authenticated routes with app layout
  layout("routes/app-layout.tsx", [
    index("routes/dashboard.tsx"),
    route("crm", "routes/crm.tsx"),
    route("crm/new", "routes/crm-new.tsx"),
    route("crm/:id", "routes/crm-detail.tsx"),
    route("crm/:id/edit", "routes/crm-edit.tsx"),
    route("crm/:id/contacts/new", "routes/crm-contacts-new.tsx"),
    route("processes", "routes/processes.tsx"),
    route("processes/kanban", "routes/processes-kanban.tsx"),
    route("processes/new", "routes/processes-new.tsx"),
    route("processes/:id", "routes/processes-detail.tsx"),
    route("processes/:id/edit", "routes/processes-edit.tsx"),
    route("calculator", "routes/calculator.tsx"),
    route("ncm", "routes/ncm.tsx"),
    route("financial", "routes/financial.tsx"),
    route("financial/new", "routes/financial-new.tsx"),
    route("financial/:id", "routes/financial-detail.tsx"),
    route("financial/report", "routes/financial-report.tsx"),
    route("financial/receipt", "routes/financial-receipt.tsx"),
    route("financial/cashflow", "routes/financial-cashflow.tsx"),
    route("financial/cashflow/new", "routes/financial-cashflow-new.tsx"),
    route("financial/cashflow/import", "routes/financial-cashflow-import.tsx"),
    route("financial/categories", "routes/financial-categories.tsx"),
    route("settings", "routes/settings.tsx"),
    route("agents", "routes/agents.tsx"),
    route("automations", "routes/automations.tsx"),
    route("automations/overview", "routes/automations-overview.tsx"),
    route("automations/health", "routes/automations-health.tsx"),
    route("automations/dashboard", "routes/automations-dashboard.tsx"),
    route("crm/pipeline", "routes/crm-pipeline.tsx"),
    route("audit", "routes/audit.tsx"),
    route("ai-usage", "routes/ai-usage.tsx"),
    route("public-procurement", "routes/public-procurement.tsx"),
    route("public-procurement-new", "routes/public-procurement-new.tsx"),
    route("public-procurement/:noticeId", "routes/public-procurement.$noticeId.tsx"),
    route("personal-life", "routes/personal-life.tsx"),
    route("personal-life/finances", "routes/personal-life.finances.tsx"),
    route("personal-life/finances/analytics", "routes/personal-life.finances.analytics.tsx"),
    route("personal-life/investments", "routes/personal-life.investments.tsx"),
    route("personal-life/routines", "routes/personal-life.routines.tsx"),
    route("personal-life/goals", "routes/personal-life.goals.tsx"),
    route("personal-life/promotions", "routes/personal-life.promotions.tsx"),
    route("personal-life/timeoff", "routes/personal-life.timeoff.tsx"),
    route("personal-life/bills", "routes/personal-life.bills.tsx"),
    route("personal-life/pessoas", "routes/personal-life.pessoas.tsx"),
    route("personal-life/tasks", "routes/personal-life.tasks.tsx"),
    route("personal-life/wishlist", "routes/personal-life.wishlist.tsx"),
    route("personal-life/radio-monitor", "routes/personal-life.radio-monitor.tsx"),
    route("knowledge/prompting", "routes/knowledge.prompting.tsx"),
    route("changelog", "routes/changelog.tsx"),
    route("other-business", "routes/other-business.tsx"),
    route("other-business/internet", "routes/other-business.internet.tsx"),
  ]),

  // API routes
  route("logout", "routes/logout.tsx"),
  route("api/theme", "routes/api.theme.tsx"),
  route("api/locale", "routes/api.locale.tsx"),
  route("api/exchange-rate", "routes/api.exchange-rate.tsx"),
  route("api/document/:id/download", "routes/api.document-download.tsx"),
  route("api/chat", "routes/api.chat.tsx"),
  route("api/enrich-cnpj", "routes/api.enrich-cnpj.tsx"),
  route("api/ncm-taxes", "routes/api.ncm-taxes.tsx"),
  route("api/health", "routes/api.health.tsx"),
  route("api/notifications", "routes/api.notifications.tsx"),
  route("api/telegram-webhook", "routes/api.telegram-webhook.tsx"),
  route("api/ocr-extract", "routes/api.ocr-extract.tsx"),
  route("api/promotion-extract", "routes/api.promotion-extract.tsx"),
  route("api/promotion-strategy", "routes/api.promotion-strategy.tsx"),
  route("api/approve-process", "routes/api.approve-process.tsx"),
  route("api/automations-run", "routes/api.automations-run.tsx"),
  route("api/automations-logs", "routes/api.automations-logs.tsx"),
  route("api/automations-logs-cleanup", "routes/api.automations-logs-cleanup.tsx"),
  route("api/automations-cron-health", "routes/api.automations-cron-health.tsx"),
  route("api/automations-simulate", "routes/api.automations-simulate.tsx"),
  route("api/automations-webhook-listener", "routes/api.automations-webhook-listener.tsx"),
  route("api/automations-schedule", "routes/api.automations-schedule.tsx"),
  route("api/automations-history", "routes/api.automations-history.tsx"),
  route("api/automations-duplicate", "routes/api.automations-duplicate.tsx"),
  route("api/automations-notify-failure", "routes/api.automations-notify-failure.tsx"),
  route("api/automations-test-webhook", "routes/api.automations-test-webhook.tsx"),
  route("api/public-procurement-notices", "routes/api.public-procurement-notices.tsx"),
  route("api/public-procurement-processes", "routes/api.public-procurement-processes.tsx"),
  route("api/public-procurement-alerts", "routes/api.public-procurement-alerts.tsx"),
  route("api/tr-templates", "routes/api.tr-templates.tsx"),
  route("api/personal-finance", "routes/api.personal-finance.tsx"),
  route("api/personal-investments", "routes/api.personal-investments.tsx"),
  route("api/personal-routines", "routes/api.personal-routines.tsx"),
  route("api/promotions", "routes/api.promotions.tsx"),
  route("api/personal-goals", "routes/api.personal-goals.tsx"),
  route("api/life-run", "routes/api.life-run.tsx"),
  route("api/financial-categories", "routes/api.financial-categories.tsx"),
  route("api/company-profile", "routes/api.company-profile.tsx"),
  route("api/openclaw-telegram-webhook", "routes/api.openclaw-telegram-webhook.tsx"),
  route("api/radio-monitor-config", "routes/api.radio-monitor-config.tsx"),
  route("api/radio-monitor-event", "routes/api.radio-monitor-event.tsx"),
  route("api/radio-monitor-song", "routes/api.radio-monitor-song.tsx"),
  route("api/scpc-search", "routes/api.scpc-search.tsx"),

  // Catch-all 404
  route("*", "routes/$.tsx"),
] satisfies RouteConfig;
